
contentdir = "src"
layoutdir = "hugo/layouts"
archetypedir = "hugo/archetypes"
datadir = "hugo/data"
staticdir = "hugo/static"
themesdir = "hugo/themes"

hasCJKLanguage = true


baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "cormoran's note"
languageCode = "ja"

disqusShortname="cormoran"

[params]
	author = "cormoran"
	description = "競技プログラミング系の記録"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/icon.jpg"
	# or use Gravatar by adding your email address to generate a unique avatar
	#gravatar = "cormoran707@email.com"

    headerText = "asdfgh"
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "cormoran"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		#email = "cormoran707@gmail.com"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "cormoran"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = "cormoran707"
		wordpress = ""
		youtube = ""
		# Insert your Xing Profile-ID not your login name
		xing = ""


