contentdir = "src"
layoutdir = "hugo/layouts"
archetypedir = "hugo/archetypes"
datadir = "hugo/data"
staticdir = "hugo/static"
themesdir = "hugo/themes"

hasCJKLanguage = true

baseurl = "http://procon.cormoran-web.com"
languageCode = "ja"
title = "競技プログラミングの記録"
copyright = "2017 cormoran-web.com"
author = "cormoran"
disqusShortname = "cormoran-web"
googleAnalytics = "UA-68985854-1"

[[menu.main]]
	name = "Home"
	weight = 0
	identifier = "home"
	url = "/"

[[menu.main]]
	name = "Writeup"
	weight = 1
	identifier = "writeup"
	url = "/contest"

[[menu.main]]
	name = "Library"
	weight = 2
	identifier = "library"
	url = "/library/menu"

[[menu.main]]
	name = "Blog"
	weight = 3
	identifier = "blog"
	url = "http://blog.cormoran-web.com"

[[menu.main]]
	name = "About Me"
	weight = 4
	identifier = "profile"
	url = "http://blog.cormoran-web.com/profile/"

[taxonomies]
	tag = "tags"
	category = "categories"
	contest = "contests"
	problemtype = "problemtypes"

[params]
author = "cormoran"
short_profile = "継続力がないのでこつこつと解説を書くのは諦めました"
logo = "/img/icon.jpg"
twitter = "cormoran707"
github = "cormoran"
# google_custom_search = "007779444469775643741:gxf1addhpnq"